### ISSUE TITLE
Gson dependency

### ISSUE THREAD

**Issue by mrlem** [dilrajsingh1997/safe-compose-args#1]
The gradle dependency to **Gson** should should probably be *api*, and *not implementation* (otherwise the user has to import it manually as the generated code depends on it).

**Comment by dilrajsingh1997** [comment]
Yes this need to be changed, will change this in the next release.

**Comment by dilrajsingh1997** [comment]
This has been addressed in the latest release. Please upgrade the dependencies to the latest version from the github README.
