### ISSUE TITLE
Conflicting declarations when building for release

### ISSUE THREAD

**Issue by Moppet12** [dilrajsingh1997/safe-compose-args#3]
Awesome tool, congrats!

I'm facing an issue that prevents to build for release my app, I hope you can help to keep using this library which provides a clean solution por params.

I have this DataClass to launch a Gallery view

```
data class GalleryList(
    var files: ArrayList<MediaFile>,
    var activeIndex: Int
) : Parcelable {
    constructor(parcel: Parcel) : this(
        arrayListOf<MediaFile>().apply {
            parcel.readList(this, MediaFile::class.java.classLoader)
        },
        parcel.readInt()
    )

    override fun writeToParcel(parcel: Parcel, flags: Int) {
        parcel.writeList(files)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object CREATOR : Parcelable.Creator<MediaFile> {
        @RequiresApi(Build.VERSION_CODES.Q)
        override fun createFromParcel(parcel: Parcel): MediaFile {
            return MediaFile()
        }

        override fun newArray(size: Int): Array<MediaFile?> {
            return arrayOfNulls(size)
        }
    }
}
```

And when trying to build for release prompts this error:

> Conflicting declarations: public val GalleryPage_GalleryListNavType: NavType<GalleryList>, public val GalleryPage_GalleryListNavType: NavType<GalleryList>

My thoughts are that library is building the same class for both environments (debug and release) and then are conflicting

**Comment by Moppet12** [comment]
Temporary I found a workaround for this issue, clean project before building any target to avoid namespace overlapping.

**Comment by dilrajsingh1997** [comment]
Yes this issue is prevelant. when building for release, the generated code conflicts with the generated code of debug variant. Will fix this in the next release.

**Comment by dilrajsingh1997** [comment]
This is an issue with the configuration of KSP. Replacing the following 
```
kotlin.sourceSets.main {
    kotlin.srcDirs(
        file("$buildDir/generated/ksp/"),
    )
}
```
with
```
androidComponents.onVariants { variant ->
    kotlin.sourceSets.findByName(variant.name)?.kotlin?.srcDirs(
        file("$buildDir/generated/ksp/${variant.name}/kotlin")
    )
}
```
This will make android studio include only the generated files for the current variant of the project.
If this helps, please let me know and will close the issue accordingly.
